import Link from 'next/link';
import Eomji from './../public/eomji.jpg';
import Image from 'next/image';
import './output.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='w-screen flex'>
        <div className='w-[230px] min-h-screen pt-10 border-r'>
          <div className='flex flex-col items-center'>
            <Image
              src={Eomji}
              alt='profile img'
              className='w-[150px] rounded-full'
            />
            <span className='mt-3 font-semibold'>Eomji</span>
          </div>
          <ul className='flex flex-col gap-2 mt-5 w-[150px] mr-auto ml-auto'>
            <li className='p-1'>
              <Link href='/'>All</Link>
            </li>
            <li className='p-1'>
              <Link href='/cs'>CS</Link>
            </li>
            <li className='p-1'>
              <Link href='/algorithm'>Algorithm</Link>
            </li>
          </ul>
        </div>
        <div className='min-h-screen flex-[8] pt-10 pl-10 pr-10'>
          {children}
        </div>
      </body>
    </html>
  );
}

